from bs4 import BeautifulSoup
from colorama import init, Fore
init()


def parse(data: bytes):
    soup = BeautifulSoup(data, features="html.parser")
    msg = soup.find("div", {"role": "list"}).find_all("div", {"role": "listitem"})[-1]

    questions_div = msg.find("div", {"bgcolor": "white"})
    grade = questions_div.find("div", {"style": "padding-left:10px;display:inline-block;border:1px solid black"})
    personal = questions_div.find("table", {"cellspacing": "12"})
    data = BeautifulSoup(str(questions_div).split("<p></p>")[1], features="html.parser")
    questions = [x.parent for x in questions_div.find_all("p", {"style": "width:400px;font-size:large"})]
    for question in questions:
        if "//ssl.gstatic.com/" in str(question) \
                or "This email was generated by Flubaroo, a free tool for grading and assessments." in str(
                question):
            print('continue')
            continue
        valid = question.find("div", {"style": "width:100%;font-size:xx-large;text-align:right"}).text == "Correct"
        answer = question.find("p", {"style": "width:400px;font-size:medium"})
        question = question.find("p", {"style": "width:400px;font-size:large"})
        print(f"{Fore.GREEN if valid else Fore.RED}{valid}{Fore.RESET}, {question.text}, {answer.text}")