from bs4 import BeautifulSoup
from colorama import init, Fore
init()
debugging = False

def parse(data: bytes):
    soup = BeautifulSoup(data, features="html.parser")
    msg = soup.find("div", {"role": "list"}).find_all("div", {"role": "listitem"})[-1]

    questions_div = msg.find("div", {"bgcolor": "white"})
    form_name = questions_div.find("p").find("b").text
    grade = questions_div.find("div", {"style": "padding-left:10px;display:inline-block;border:1px solid black"})
    personal = [i.text for i in questions_div.find("table", {"cellspacing": "12"}).find_all("b")]
    
    name = personal.pop()
    lastname = personal.pop()
    email = personal.pop()
    date = personal.pop()
    
    questions = [x.parent.parent if str(x.parent).startswith("<span class=") else x.parent for x in questions_div.find_all("p", {"style": "width:400px;font-size:large"})]
    results = {
        "form": form_name,
        "email": email,
        "name": name,
        "lastname": lastname,
        "date": date,
        "questions": {}
    }
    for question in questions:
        if "//ssl.gstatic.com/" in str(question) or "This email was generated by Flubaroo, a free tool for grading and assessments." in str(question):
            continue
        valid = question.find("div", {"style": "width:100%;font-size:xx-large;text-align:right"}).text == "Correct"
        
        answer = question.find("p", {"style": "width:400px;font-size:medium"}).text
        answer = answer.split("Your Answer: ", 1)[1]

        question = question.find("p", {"style": "width:400px;font-size:large"}).text
        
        results['questions'][question] = {
            "question": question,
            "answer": answer,
            "correct": valid
        }
        if debugging:
            print("\n"*4)
            print(f"{Fore.GREEN if valid else Fore.RED}{valid}{Fore.RESET}:\n\t{Fore.CYAN}{question}{Fore.RESET}\n\n\tYour Answer: {Fore.GREEN if valid else Fore.RED}{answer}{Fore.RESET}")
    return results
